```{r include=FALSE}

library(xtable)
library(kableExtra)
library(tidyverse)
library(tidyr)
library(pander)
library(ggplot2)
library(ggthemes)
library(psych)
library(MASS)
library(readr)
library(corrplot)
library(lme4)
library(nlme)
library(faraway)
library(rpca)
library(leaps)
library(olsrr)
library(Sleuth3)
library(caTools)
library(tree)
library(aod)
library(ISLR)
library(randomForest)
```
